-- Criação da tabela TB_USUARIO
CREATE TABLE TB_USUARIO (
                            idUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            email VARCHAR2(255) NOT NULL,
                            nome VARCHAR2(100) NOT NULL,
                            senha VARCHAR2(100) NOT NULL,
                            dataCriacao DATE DEFAULT SYSDATE
);

-- Criação da tabela TB_JOGO
CREATE TABLE TB_JOGO (
                         idJogo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR2(100) NOT NULL,
                         nota NUMBER(3,1) CHECK (nota >= 0 AND nota <= 10),
                         idUsuario NUMBER REFERENCES TB_USUARIO(idUsuario) ON DELETE CASCADE
);

-- Criação da tabela TB_COMENTARIO
CREATE TABLE TB_COMENTARIO (
                               idComentario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               nome VARCHAR2(100) NOT NULL,
                               descricao VARCHAR2(500) NOT NULL,
                               idJogo NUMBER REFERENCES TB_JOGO(idJogo) ON DELETE CASCADE,
                               idUsuario NUMBER REFERENCES TB_USUARIO(idUsuario) ON DELETE CASCADE
);
